examen2/nflexamen/core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns = [
    path('estadio/lista/',views.listaestadios.as_view(), name="listaestadio"),
    path('estadio/crear/',views.Createestadio.as_view(), name="crestadio"),
    path('estadio/detalles/<int:pk>/', views.Detailestadio.as_view(), name= "restadio"),
    path('estadio/actualizar/<int:pk>/', views.Updateestadio.as_view(), name= "uestido"),
    path('estadio/borrar/<int:pk>/', views.Deleteestadio.as_view(), name= "destadio"),
    
    path('equipo/lista/',views.Listaequipos.as_view(), name="listaequipo"),
    path('equipo/crear/',views.Createequipos.as_view(), name="crequipo"),
    path('equipo/detalles/<int:pk>/', views.Detailequipos.as_view(), name= "requipo"),
    path('equipo/actualizar/<int:pk>/', views.Updateequipos.as_view(), name= "uequipo"),
    path('equipo/borrar/<int:pk>/', views.Deleteequipos.as_view(), name= "dequipo"),

    path('ciudad/lista/',views.listaciudades.as_view(), name="listaciudad"),
    path('ciudad/crear/',views.Createcuidad.as_view(), name="crciudad"),
    path('ciudad/detalles/<int:pk>/', views.Detailciudad.as_view(), name= "rciudad"),
    path('ciudad/actualizar/<int:pk>/', views.Updateciudad.as_view(), name= "uciudad"),
    path('ciudad/borrar/<int:pk>/', views.Deleteciudad.as_view(), name= "dciudad"),
]

examen2/nflexamen/home/urls.py
from django.urls import path, include
from home import views

app_name="home"
urlpatterns = [
   path('', views.inicio.as_view(),name='inicio') 
]

examen2/nflexamen/nflexamen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('core.urls'))
]

examen2/nflexamen/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:inicio' %}">NFL</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaciudad' %}">Ciudades</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaequipo' %}">Equipos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaestadio' %}">Estadios</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <footer class="bg-light text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Copyright:
      <a class="text-dark" href="https://www.nfl.com/">NFL.com</a>
    </div>
    <!-- Copyright -->
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>