examen2/nflexamen/core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns = [
    path('estadio/lista/',views.listaestadios.as_view(), name="listaestadio"),
    path('estadio/crear/',views.Createestadio.as_view(), name="crestadio"),
    path('estadio/detalles/<int:pk>/', views.Detailestadio.as_view(), name= "restadio"),
    path('estadio/actualizar/<int:pk>/', views.Updateestadio.as_view(), name= "uestido"),
    path('estadio/borrar/<int:pk>/', views.Deleteestadio.as_view(), name= "destadio"),
    
    path('equipo/lista/',views.Listaequipos.as_view(), name="listaequipo"),
    path('equipo/crear/',views.Createequipos.as_view(), name="crequipo"),
    path('equipo/detalles/<int:pk>/', views.Detailequipos.as_view(), name= "requipo"),
    path('equipo/actualizar/<int:pk>/', views.Updateequipos.as_view(), name= "uequipo"),
    path('equipo/borrar/<int:pk>/', views.Deleteequipos.as_view(), name= "dequipo"),

    path('ciudad/lista/',views.listaciudades.as_view(), name="listaciudad"),
    path('ciudad/crear/',views.Createcuidad.as_view(), name="crciudad"),
    path('ciudad/detalles/<int:pk>/', views.Detailciudad.as_view(), name= "rciudad"),
    path('ciudad/actualizar/<int:pk>/', views.Updateciudad.as_view(), name= "uciudad"),
    path('ciudad/borrar/<int:pk>/', views.Deleteciudad.as_view(), name= "dciudad"),
]

examen2/nflexamen/nflexamen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('core.urls'))
]

examen2/nflexamen/core/models.py
from django.db import models

class Ciudades(models.Model):
    Nombre = models.CharField(max_length=35, default= "Minneapolis")
    Estado = models.CharField(max_length=15, default= "Minnesota")
    Descripcion = models.CharField(max_length=555, default= "Esta ciudad estadounidense es aficionada a los Minnesota")
    fecha= models.DateField(auto_now_add=True)
    def __str__(self):
        return self.Nombre

class Equipos(models.Model):
    Nombre = models.CharField(max_length=35, default= "Viking")
    Ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
    Descripcion = models.CharField(max_length=555, default= "Este equipo se formo en 1990")
    fecha= models.DateField(auto_now_add=True)
    def __str__(self):
        return self.Nombre

class Estadios(models.Model):
    Nombre = models.CharField(max_length=35, default= "Bank Stadium")
    Equipos= models.ForeignKey(Equipos, on_delete=models.CASCADE)
    Descripcion = models.CharField(max_length=555, default= "El estadio abrio sus puertas en 2001")
    fecha= models.DateField(auto_now_add=True)
    def __str__(self):
        return self.Nombre

examen2/nflexamen/core/forms.py
from django import forms
from .models import *

##estadios

class estadiosforms(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Equipos": forms.Select(attrs={"class":"form-select form-control"}),
            "Descripcion" : forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }
        labels = {
            "Descripcion" : "Descripción", 
            }



class actulizarestadiosforms(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Equipos": forms.Select(attrs={"class":"form-select form-control"}),
            "Descripcion" : forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }
        labels = {
            "Descripcion" : "Descripción", 
            }

##equpos

class equipoforms(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Ciudad": forms.Select(attrs={"class":"form-select form-control"}),
            "Descripcion" : forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }
        labels = {
            "Descripcion" : "Descripción", 
            }
        
class actualizarequiposforms(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Ciudad": forms.Select(attrs={"class":"form-select form-control"}),
            "Descripcion" : forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }
        labels = {
            "Descripcion" : "Descripción", 
            }

##ciudad

class ciudadesforms(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Estado": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del estado"}),
            "Descripcion" : forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }
        labels = {
            "Descripcion" : "Descripción", 
            }

class actualizarciudadesforms(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "Nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "Estado": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del estado"}),
            "Descripcion" : forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            }
        labels = {
            "Descripcion" : "Descripción", 
            }

examen2/nflexamen/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *



# Create your views here.

##STADIOS

class listaestadios(generic.View):
    template_name = "core/estadio/listaestadio.html"
    context = {}

    def get(self, request, *args, **kwargs):
        Estadio = Estadios.objects.all()
        self.context = {
            "Estadios": Estadio
        }
        return render(request, self.template_name,self.context)


class Detailestadio(generic.DetailView):
    template_name = "core/estadio/restadio.html"
    model = Estadios


class Createestadio(generic.CreateView):
    template_name = "core/estadio/cestadio.html"
    model = Estadios
    form_class = estadiosforms
    success_url = reverse_lazy("core:listaestadio")


class Updateestadio(generic.UpdateView):
    template_name = "core/estadio/uestido.html"
    model = Estadios
    form_class = actulizarestadiosforms
    success_url = reverse_lazy("core:listaestadio")

class Deleteestadio(generic.DeleteView):
    template_name = "core/estadio/destadio.html"
    model = Estadios
    success_url = reverse_lazy("core:listaestadio")


##EQUIPOS

class Listaequipos(generic.View):
    template_name = "core/equipo/listaequipo.html"
    context = {}

    def get(self, request, *args, **kwargs):
        equipo =  Equipos.objects.all()
        self.context = {
            "Equipos": equipo
        }
        return render(request, self.template_name,self.context)
    
class Createequipos(generic.CreateView):
    template_name = "core/equipo/cequipo.html"
    model = Equipos
    form_class = equipoforms
    success_url = reverse_lazy("core:listaequipo")

class Detailequipos(generic.DetailView):
    template_name = "core/equipo/requipo.html"
    model = Equipos

class Updateequipos(generic.UpdateView):
    template_name = "core/equipo/uequipo.html"
    model = Equipos
    form_class = actualizarequiposforms
    success_url = reverse_lazy("core:listaequipo")

class Deleteequipos(generic.DeleteView):
    template_name = "core/equipo/dequipo.html"
    model = Equipos
    success_url = reverse_lazy("core:listaequipo")

##CIUDAD

class listaciudades(generic.View):
    template_name = "core/ciudad/listaciudad.html"
    context = {}

    def get(self, request, *args, **kwargs):
        Ciudad = Ciudades.objects.all()
        self.context = {
            "Ciudades": Ciudad
        }
        return render(request, self.template_name,self.context)

class Createcuidad(generic.CreateView):
    template_name = "core/ciudad/cciudad.html"
    model = Ciudades
    form_class = ciudadesforms
    success_url = reverse_lazy("core:listaciudad")

class Detailciudad(generic.DetailView):
    template_name = "core/ciudad/rciudad.html"
    model = Ciudades

class Updateciudad(generic.UpdateView):
    template_name = "core/ciudad/uciudad.html"
    model = Ciudades
    form_class = actualizarciudadesforms
    success_url = reverse_lazy("core:listaciudad")

class Deleteciudad(generic.DeleteView):
    template_name = "core/ciudad/dciudad.html"
    model = Ciudades
    success_url = reverse_lazy("core:listaciudad")

examen2/nflexamen/templates/core/equipo/cequipo.html
{% extends "base/base.html" %}

{% block title %}
Crear un equipo
{% endblock title %}

{% block content %}
<title>Crear equipo</title>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Crear equipo</button>
        <a href="{% url 'core:listaequipo' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/nflexamen/templates/core/equipo/dequipo.html
{% extends "base/base.html" %}

{% block title %}
Borrar equipo
{% endblock title %}

{% block content %}
<title>Borrar equipo</title>
    <form action="" method="post">
        {% csrf_token %}
        ¿Seguro de borrar: {{ object.Nombre }}?
        <button type="submit" class="btn btn-outline-danger">Borrar equipo</button>
        <a href="{% url 'core:listaequipo' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/nflexamen/templates/core/equipo/listaequipo.html
{% extends 'base/base.html' %}

{% block title %} Lista de Equipos
{% endblock title %}

{% block content %}
<title>Lista equipos</title>

    <a href="{% url 'core:crequipo' %}" class="btn btn-outline-success form-control">Crear un nuevo equipo</a>
    <table class="table table-striped table-hover">
        <thead class="table-info">
            <th style="color: #353535;">ID</th>
            <th style="color: #353535;">Nombre</th>
            <th></th>
            <th style="color: #353535;">Acciones</th>
            <th></th>

        </thead>
        <tbody>
            {% for Equipos in Equipos %}
                <tr>
                    <td>{{ Equipos.id }}</td>
                    <td>{{ Equipos.Nombre }}</td>
                    <td><a href="{% url 'core:requipo' Equipos.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:uequipo' Equipos.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:dequipo' Equipos.id %}" class="btn btn-outline-danger">Borrar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

examen2/nflexamen/templates/core/equipo/requipo.html
{% extends "base/base.html" %}

{% block title %}
Detalles del equipo
{% endblock title %}


{% block content %}
<title>Detalles equipo</title>
<h6>Nombre: </h6>{{ object.Nombre }}
<br>
<h6>Ciudad: </h6>{{ object.Ciudad }}
<br>
<h6>Descripción: </h6>{{ object.Descripcion }}
<br>
<h6>Fecha de creación: </h6>
{{ object.fecha }}
<br>
  <a href="{% url 'core:listaequipo' %}">Regresar</a>
{% endblock content %}

examen2/nflexamen/templates/core/equipo/uequipo.html
{% extends "base/base.html" %}

{% block title %}
Actualizar equipo
{% endblock title %}

{% block content %}
<title>Actualizar equipo</title>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar equipo</button>
        <a href="{% url 'core:listaequipo' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}